// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pagination.proto

/*
Package people is a generated protocol buffer package.

It is generated from these files:
	pagination.proto

It has these top-level messages:
	PageOptions
*/
package people

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type PageOptions struct {
	PageSize  int32  `protobuf:"varint,1,opt,name=page_size,json=pageSize" json:"page_size,omitempty"`
	PageToken string `protobuf:"bytes,2,opt,name=page_token,json=pageToken" json:"page_token,omitempty"`
}

func (m *PageOptions) Reset()                    { *m = PageOptions{} }
func (m *PageOptions) String() string            { return proto.CompactTextString(m) }
func (*PageOptions) ProtoMessage()               {}
func (*PageOptions) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *PageOptions) GetPageSize() int32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *PageOptions) GetPageToken() string {
	if m != nil {
		return m.PageToken
	}
	return ""
}

func init() {
	proto.RegisterType((*PageOptions)(nil), "people.PageOptions")
}

func init() { proto.RegisterFile("pagination.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 118 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x28, 0x48, 0x4c, 0xcf,
	0xcc, 0x4b, 0x2c, 0xc9, 0xcc, 0xcf, 0xd3, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2b, 0x48,
	0xcd, 0x2f, 0xc8, 0x49, 0x55, 0xf2, 0xe4, 0xe2, 0x0e, 0x48, 0x4c, 0x4f, 0xf5, 0x2f, 0x00, 0xc9,
	0x15, 0x0b, 0x49, 0x73, 0x71, 0x16, 0x24, 0xa6, 0xa7, 0xc6, 0x17, 0x67, 0x56, 0xa5, 0x4a, 0x30,
	0x2a, 0x30, 0x6a, 0xb0, 0x06, 0x71, 0x80, 0x04, 0x82, 0x33, 0xab, 0x52, 0x85, 0x64, 0xb9, 0xb8,
	0xc0, 0x92, 0x25, 0xf9, 0xd9, 0xa9, 0x79, 0x12, 0x4c, 0x0a, 0x8c, 0x1a, 0x9c, 0x41, 0x60, 0xe5,
	0x21, 0x20, 0x81, 0x24, 0x36, 0xb0, 0xc9, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0x25, 0x8d,
	0x26, 0x45, 0x6d, 0x00, 0x00, 0x00,
}
